rt_whisper:
    default_hyperparameter_path: "./default_hyperparameter.yml"

    huggingface:
        path: "openai/whisper-large-v3"

    log:
        level: 20 # INFO: 20, DEBUG: 10
        dir_path: ${RT_WHISPER_LOG_DIR:./logs}
        # 용량 엄청 큼. 따라서 필요시 활성화
        file_level: 20 # INFO: 20, DEBUG: 10

rt_whisper_optimizer:
    log:
        level: 10 # INFO: 20, DEBUG: 10
        dir_path: ${RT_WHISPER_OPTIMIZER_LOG_DIR:./logs}
        # 용량 엄청 큼. 따라서 필요시 활성화
        file_level: 20 # INFO: 20, DEBUG: 10
