class Settings:
  DEFAULT_SAMPLE_RATE = 16000

  MODEL_SIZE = "large-v3"
  MODEL_DEVICE = "cuda"
  MODEL_COMPUTE_TYPE = "int8"
  MODEL_BEAM_SIZE = 3
  MODEL_BATCH_SIZE = 8
  MODEL_SAMPLE_RATE = 16000

  MODEL_WORD_MAX_PREV_TIME = 3

  MODEL_SENTENCE_MAX_PREV_SENTENCE = 1

  THREAD_MAX_WORKERS = 20

  MIN_AUDIO_DURATION = 2 * MODEL_SAMPLE_RATE # 2 seconds