name: RTWhisper-Dev
services:
    dev:
        build:
            context: ..
            dockerfile: .devcontainer/Dockerfile
        volumes:
            - ../:/workspaces/dev
            #   - ../.model/huggingface:/root/.cache/huggingface
            - F:/Models/huggingface:/root/.cache/huggingface:rw
            #   - ../.model/torch:/root/.cache/torch
            - F:/Models/torch:/root/.cache/torch:rw
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu]
        command: ["tail", "-f", "/dev/null"]
