name: RTWhisper-Dev
services:
    dev:
        build:
            context: ..
            dockerfile: .devcontainer/Dockerfile
        volumes:
            - ../:/workspaces/dev

            #   - ../.model/huggingface:/root/.cache/huggingface
            - F:/docker-volume/cache/huggingface:/home/vscode/.cache/huggingface
            #   - ../.model/torch:/root/.cache/torch
            - F:/docker-volume/cache/torch:/home/vscode/.cache/torch

            - /workspaces/dev/.venv # no sync

            # dataset
            - F:/docker-volume/datasets:/workspaces/dev/.datasets:ro
            - F:/docker-volume/datasets/asr-rankformer-datasets:/workspaces/dev/.datasets/asr-rankformer-datasets:rw
            - F:/docker-volume/datasets/ami:/workspaces/dev/.datasets/ami:rw
            - F:/docker-volume/datasets/tedlium:/workspaces/dev/.datasets/tedlium:rw
            - F:/docker-volume/datasets/vox_populi:/workspaces/dev/.datasets/vox_populi:rw
            - F:/docker-volume/datasets/libri_speech:/workspaces/dev/.datasets/libri_speech:rw

            # storage
            - F:/docker-volume/storage/rt-whisper:/workspaces/dev/.storage:rw
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu]
        command: ["tail", "-f", "/dev/null"]
